# https://github.com/SeleniumHQ/docker-selenium
# Set ExecutionPlatform from `project.properties` ,  "localhost:4444" , "Linux-64" and "headlessExecution"
# To execute this docker-compose yml file use `docker-compose -f docker-compose.yml up --scale chrome=4 -d`
# Add the `-d` flag at the end for detached execution
# http://localhost:4444/grid/console
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose.yml down --remove-orphans`
version: "3"
services:

   selenium-hub:
      image: selenium/hub:4.1.2
      container_name: selenium-hub
      ports:
         - "4442:4442"
         - "4443:4443"
         - "4444:4444"
      environment:
         GRID_MAX_SESSION: 4
         GRID_BROWSER_TIMEOUT: 300
         GRID_TIMEOUT: 300


   chrome:
      image: selenium/node-chrome:4.1.2
      shm_size: 2gb
      depends_on:
         - selenium-hub
      environment:
         - SE_EVENT_BUS_HOST=selenium-hub
         - SE_EVENT_BUS_PUBLISH_PORT=4442
         - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

   edge:
      image: selenium/node-edge:4.1.2
      shm_size: 2gb
      depends_on:
         - selenium-hub
      environment:
         - SE_EVENT_BUS_HOST=selenium-hub
         - SE_EVENT_BUS_PUBLISH_PORT=4442
         - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

   firefox:
      image: selenium/node-firefox:4.1.2
      shm_size: 2gb
      depends_on:
         - selenium-hub
      environment:
         - SE_EVENT_BUS_HOST=selenium-hub
         - SE_EVENT_BUS_PUBLISH_PORT=4442
         - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

